### ISSUE TITLE
Incorrect order of age bands when plotting attendances and admissions by age and gender

### ISSUE THREAD

**Issue by Wartynas** [HorridTom/hospitalflow#103] opened 2022-02-09 10:14 UTC
Having plotted `ae_attendances_admissions_age_sex()` (see [here](https://github.com/HorridTom/hospitalflow/blob/868b676dd2af0f2a29d22276f6c3d86b20303075/R/ae_attendances_admissions_age_sex.R#L18) for the definition), I noticed that the 5-9 year age band is located in the middle of x axis.

![ae_attendances_admissions_age_sex](https://user-images.githubusercontent.com/55479800/153177126-d11ba054-47d2-4bf5-991d-9be1f08db440.png)

**Comment by Wartynas** [comment] 2022-02-09 10:19
As we discussed with @HorridTom, a possible solution could be creating a config file for age-band (e.g., `age_band_start_levels`) in the example config, which would prevent age bands from being ordered alphabetically (which is the case now). We might also consider adding a warning to the function (or maybe all of the functions) that would detect unexpected behaviors such as this one.

**Comment by HorridTom** [comment] 2022-02-09 12:40
@ImogenConnorHelleur this is an interesting one I hadn't spotted, not sure if you had seen it... When discussing with @Wartynas yesterday I wasn't sure of the relationship between the `example-config` files and the data in the `data` folder - i.e. assuming that the correct fix here is to create config files `age_band_start_levels.rds` in `example-config/inpatient` and `example-config/ed`, how then would new datasets `data/ed_data.rda` and `data/inpatient_data.rda` (and hence `data/spell_table.rda`) be created? Is that something you ran manually using `import_standardise_bind` and `make_spell_table`? If so, is this something @Wartynas could do, or is there some process we need to follow specifically to create the example data? 

@ImogenConnorHelleur @Wartynas perhaps this is something you can discuss when you meet on Monday?

**Comment by HorridTom** [comment] 2022-02-09 12:46
@Wartynas could you start on this (on a new branch) by (for now) just writing a test to capture the problem? You could use a subset of the example data in the `data` folder as test data for this. You can add another `test_that` to the bottom of the [existing test file for this function](https://github.com/HorridTom/hospitalflow/blob/master/tests/testthat/test_attend_adm_age_sex.R). Place any data used for the test in the corresponding subfolder of `tests/testthat/testdata`. Your new test should fail for now, because the problem is not yet fixed.

**Comment by Wartynas** [comment] 2022-02-09 16:25
Hey @HorridTom, just wrote a test for 5-9 year age group (see [here](https://github.com/HorridTom/hospitalflow/blob/16257df6bb7a7e4faf1f4cc78fc7e1e571cac3f3/tests/testthat/test_attend_adm_age_sex.R#L69)). Also, since this function did not have a corresponding data folder under `tests/testthat/testdata`, I created one named `attend_adm_age_sex` and put a subset of `data/spell_table.rds` there. I am not sure if the test I wrote (my first one!) is in line with what is considered to be a good practice, so I am looking forward to hearing your feedback. I could rewrite it in a different way if you think it's needed. Anyway, I made a PR for you to review the test.

Also, to test the hypothesis of alphabetical order, I thought about simulating a dataset with an age band, for example, `100-104 yrs`. I would expect it to be located somewhere around `10-14 yrs` if that hypothesis is true. I am not sure if that's worth doing or would be merely a waste of time, so I would like to hear your opinion.

**Comment by ImogenConnorHelleur** [comment] 2022-02-14 10:47
Hi @HorridTom and @Wartynas , I think it's probably easier to define the factor levels for the age bands within the `ae_attendances_admissions_age_sex()` function rather than changing any config files.

**Comment by ImogenConnorHelleur** [comment] 2022-02-14 10:57
> @ImogenConnorHelleur this is an interesting one I hadn't spotted, not sure if you had seen it... When discussing with @Wartynas yesterday I wasn't sure of the relationship between the `example-config` files and the data in the `data` folder - i.e. assuming that the correct fix here is to create config files `age_band_start_levels.rds` in `example-config/inpatient` and `example-config/ed`, how then would new datasets `data/ed_data.rda` and `data/inpatient_data.rda` (and hence `data/spell_table.rda`) be created? Is that something you ran manually using `import_standardise_bind` and `make_spell_table`? If so, is this something @Wartynas could do, or is there some process we need to follow specifically to create the example data?
> 
> @ImogenConnorHelleur @Wartynas perhaps this is something you can discuss when you meet on Monday?

The `example-config` files actually have no relationship to the data in the `data` folder. 

The data in the `data` folder are all in the standardised format so don't need to go through the `import_and_standardise()` function. 

The `example-config` files were created as an example for John to show how to load in raw excel files and standardise them. I should have the excel files relating to these config files but they're saved outside of the package because the end user will be interacting with `hospitalflow` as a libraried in package rather from inside. I think I set it up to work with this example repo: https://github.com/ImogenConnorHelleur/hospitalflow-template .  I might actually put those simulated "raw" excel files into the package for the vignette to run on.

**Closed** 2022-02-18 13:15 UTC
Labels: bug
